from __future__ import annotations

import argparse
from pathlib import Path

from .cpu import MCS51, UnsupportedOpcodeError
from .debug import (
    DebugConfigError,
    InstructionTracer,
    StepLimiter,
    WatchpointMonitor,
    format_watch_event,
    load_symbol_file,
    make_breakpoint_hook,
    merge_symbol_info,
    resolve_breakpoints,
    resolve_watchpoints,
)
from .disasm import disassemble_instruction
from .loader import LoaderError, load_program
from .project import ProjectConfigError, load_project_config
from .runtime import RuntimeConfigError, load_runtime_events, make_runtime_hook


def _parse_int(value: str) -> int:
    upper = value.upper()
    if upper.endswith("H") and upper[:-1]:
        return int(upper[:-1], 16)
    return int(value, 0)


def _parse_hex_bytes(value: str) -> bytes:
    compact = value.replace(" ", "").replace(",", "").replace("_", "")
    if compact.startswith("0x"):
        compact = compact[2:]
    if len(compact) % 2:
        raise ValueError("serial input hex must contain an even number of hex digits")
    return bytes.fromhex(compact)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Minimal 8051 / MCS-51 simulator")
    parser.add_argument("image", nargs="?", type=Path, help="HEX, BIN, or ASM program image")
    parser.add_argument("--project", type=Path, help="Project JSON configuration file")
    parser.add_argument(
        "--format",
        choices=["auto", "hex", "bin", "asm"],
        default=None,
        help="Input image format",
    )
    parser.add_argument(
        "--origin",
        type=_parse_int,
        default=None,
        help="Load address for BIN images",
    )
    parser.add_argument(
        "--entry",
        type=_parse_int,
        default=None,
        help="Execution start address",
    )
    parser.add_argument(
        "--max-instructions",
        type=int,
        default=None,
        help="Instruction execution limit",
    )
    parser.add_argument(
        "--serial-input",
        default=None,
        help="UTF-8 text queued into the emulated serial receiver",
    )
    parser.add_argument(
        "--serial-input-hex",
        default=None,
        help="Hex bytes queued into the emulated serial receiver, for example 41 42 0D 0A",
    )
    parser.add_argument(
        "--runtime",
        type=Path,
        default=None,
        help="JSON runtime events file for scheduled serial/external interrupt input",
    )
    parser.add_argument(
        "--symbols",
        type=Path,
        default=None,
        help="Symbol JSON file, typically generated by mcs51-build",
    )
    parser.add_argument(
        "--breakpoint",
        action="append",
        default=[],
        help="Breakpoint address or label, repeatable",
    )
    parser.add_argument(
        "--watch",
        action="append",
        default=[],
        help="Watch direct/bit/xram target; prefixes log:/rise:/fall:/stop: are supported, repeatable",
    )
    parser.add_argument(
        "--watch-log",
        action="store_true",
        default=None,
        help="Print watch event history after execution",
    )
    parser.add_argument(
        "--inspect",
        action="append",
        default=[],
        help="Print direct/bit/xram value after execution, repeatable",
    )
    parser.add_argument(
        "--step",
        type=int,
        default=None,
        help="Execute exactly N instructions unless another stop reason occurs first",
    )
    parser.add_argument(
        "--dump-direct",
        action="append",
        default=[],
        help="Dump direct address range as start:length, repeatable",
    )
    parser.add_argument(
        "--dump-xram",
        action="append",
        default=[],
        help="Dump XRAM range as start:length, repeatable",
    )
    parser.add_argument(
        "--trace-file",
        type=Path,
        default=None,
        help="Write instruction trace to a text file",
    )
    parser.add_argument(
        "--trace-limit",
        type=int,
        default=None,
        help="Maximum number of traced instructions",
    )
    parser.add_argument(
        "--list-symbols",
        action="store_true",
        help="Print available symbols and exit",
    )
    parser.add_argument(
        "--trace-ports",
        action="store_true",
        default=None,
        help="Print port write history",
    )
    parser.add_argument(
        "--trace-interrupts",
        action="store_true",
        default=None,
        help="Print interrupt service history",
    )
    parser.add_argument(
        "--trace-i2c",
        action="store_true",
        default=None,
        help="Print I2C transaction log",
    )
    parser.add_argument(
        "--trace-spi",
        action="store_true",
        default=None,
        help="Print SPI transaction log",
    )
    parser.add_argument(
        "--dump-iram",
        action="store_true",
        default=None,
        help="Print non-zero internal RAM bytes after execution",
    )
    parser.add_argument(
        "--dump-sfr",
        action="store_true",
        default=None,
        help="Print non-zero SFR bytes after execution",
    )
    parser.add_argument(
        "--no-tight-loop-detect",
        dest="tight_loop_detect",
        action="store_false",
        default=None,
        help="Disable early stop on repeated self-looping PC values",
    )
    return parser


def _coalesce(*values):
    for value in values:
        if value is not None:
            return value
    return None


def _coalesce_list(*values):
    merged: list[str] = []
    for value in values:
        if not value:
            continue
        merged.extend(list(value))
    return merged


def _format_serial(data: bytes) -> str:
    if not data:
        return "<empty>"
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return data.hex(" ")


def _print_registers(cpu: MCS51) -> None:
    print(
        "Registers: "
        f"PC=0x{cpu.pc:04X} "
        f"A=0x{cpu.acc:02X} "
        f"B=0x{cpu.b:02X} "
        f"PSW=0x{cpu.psw:02X} "
        f"SP=0x{cpu.sp:02X} "
        f"DPTR=0x{cpu.dptr:04X}"
    )
    print(
        "Ports: "
        f"P0=0x{cpu.read_direct(0x80):02X} "
        f"P1=0x{cpu.read_direct(0x90):02X} "
        f"P2=0x{cpu.read_direct(0xA0):02X} "
        f"P3=0x{cpu.read_direct(0xB0):02X}"
    )


def _print_nonzero_iram(cpu: MCS51) -> None:
    nonzero = [(index, value) for index, value in enumerate(cpu.iram[:0x80]) if value]
    if not nonzero:
        print("IRAM: <all zero>")
        return
    print("IRAM: " + " ".join(f"{index:02X}:{value:02X}" for index, value in nonzero))


def _print_nonzero_sfr(cpu: MCS51) -> None:
    nonzero = [
        (address, cpu.read_direct(address))
        for address in range(0x80, 0x100)
        if cpu.read_direct(address)
    ]
    if not nonzero:
        print("SFR: <all zero>")
        return
    print("SFR: " + " ".join(f"{address:02X}:{value:02X}" for address, value in nonzero))


def _print_symbols(symbols: dict[str, int]) -> None:
    if not symbols:
        print("Symbols: <none>")
        return
    print("Symbols:")
    for name, address in sorted(symbols.items(), key=lambda item: (item[1], item[0])):
        print(f"  0x{address:04X} {name}")


def _parse_range(spec: str) -> tuple[int, int]:
    if ":" not in spec:
        raise DebugConfigError(f"Invalid range spec: {spec}")
    start_text, length_text = spec.split(":", 1)
    start = _parse_int(start_text.strip())
    length = _parse_int(length_text.strip())
    if length <= 0:
        raise DebugConfigError(f"Range length must be positive: {spec}")
    return start, length


def _format_hexdump(label: str, start: int, data: list[int]) -> str:
    rendered = " ".join(f"{value:02X}" for value in data)
    return f"{label} 0x{start:04X}: {rendered}"


def _print_direct_dump(cpu: MCS51, spec: str) -> None:
    start, length = _parse_range(spec)
    data = [cpu.read_direct((start + offset) & 0xFF) for offset in range(length)]
    print(_format_hexdump("DIRECT", start & 0xFF, data))


def _print_xram_dump(cpu: MCS51, spec: str) -> None:
    start, length = _parse_range(spec)
    data = [cpu.xram[(start + offset) & 0xFFFF] for offset in range(length)]
    print(_format_hexdump("XRAM", start & 0xFFFF, data))


def _print_inspections(cpu: MCS51, specs: list[str], symbols: dict[str, int]) -> None:
    if not specs:
        return
    targets = resolve_watchpoints(specs, symbols)
    print("Inspect:")
    for target in targets:
        if target.kind == "direct":
            value = cpu.read_direct(target.address)
            print(f"  {target.name} = 0x{value:02X}")
        elif target.kind == "bit":
            value = cpu._read_bit(target.address)
            print(f"  {target.name} = {value}")
        elif target.kind == "xram":
            value = cpu.xram[target.address]
            print(f"  {target.name} = 0x{value:02X}")


def _print_watch_log(
    monitor: WatchpointMonitor,
    code_memory: bytes | bytearray,
    symbols: dict[str, int],
    source_map: dict[int, tuple[int | None, str]],
    force: bool,
) -> None:
    if not (force or monitor.has_log_only_targets):
        return

    if not monitor.events:
        print("Watch log: <no events>")
        return

    labels_by_address: dict[int, list[str]] = {}
    for name, address in symbols.items():
        labels_by_address.setdefault(address & 0xFFFF, []).append(name)

    print("Watch log:")
    for event in monitor.events:
        extras: list[str] = []
        labels = labels_by_address.get(event.pc, ())
        if labels:
            extras.append(f"LABEL={','.join(sorted(labels))}")
        extras.append(f"ASM={disassemble_instruction(code_memory, event.pc, symbols).text}")
        source_line = source_map.get(event.pc)
        if source_line:
            line_number, text = source_line
            if line_number is not None:
                extras.append(f"SRC={line_number}:{text}")
            else:
                extras.append(f"SRC={text}")
        print(
            f"  [{event.instruction_index:06d}] "
            f"PC=0x{event.pc:04X} "
            f"{format_watch_event(event)}"
            + (f" {' '.join(extras)}" if extras else "")
        )


def _auto_symbol_path(image_path: Path) -> Path | None:
    candidate = image_path.with_suffix(".sym.json")
    return candidate if candidate.exists() else None


def _resolve_path(project_path: Path | None, user_path: Path | None) -> Path | None:
    if user_path is None:
        return None
    if user_path.is_absolute():
        return user_path
    base = project_path.parent if project_path is not None else Path.cwd()
    return (base / user_path).resolve()


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        project = load_project_config(args.project) if args.project else None

        image = _coalesce(args.image, project.image if project else None)
        if image is None:
            parser.error("image or --project is required")
        image = image if isinstance(image, Path) else Path(image)

        image = _resolve_path(project.path if project else None, image) or image.resolve()
        fmt = _coalesce(args.format, project.format if project else None, "auto")
        origin = _coalesce(args.origin, project.origin if project else None, 0)
        entry = _coalesce(args.entry, project.entry if project else None, None)
        max_instructions = _coalesce(
            args.max_instructions,
            project.max_instructions if project else None,
            100_000,
        )
        serial_input = _coalesce(args.serial_input, project.serial_input if project else None, None)
        serial_input_hex = _coalesce(
            args.serial_input_hex,
            project.serial_input_hex if project else None,
            None,
        )
        runtime_path = _coalesce(args.runtime, project.runtime if project else None, None)
        runtime_path = _resolve_path(project.path if project else None, runtime_path)
        symbols_path = _coalesce(args.symbols, project.symbols if project else None, None)
        symbols_path = _resolve_path(project.path if project else None, symbols_path)
        if symbols_path is None and fmt in {"auto", "hex", "bin"}:
            symbols_path = _auto_symbol_path(image)
        trace_file = _coalesce(args.trace_file, project.trace_file if project else None, None)
        trace_file = _resolve_path(project.path if project else None, trace_file)
        trace_limit = _coalesce(args.trace_limit, project.trace_limit if project else None, None)
        trace_ports = _coalesce(args.trace_ports, project.trace_ports if project else None, False)
        trace_interrupts = _coalesce(
            args.trace_interrupts,
            project.trace_interrupts if project else None,
            False,
        )
        trace_i2c = _coalesce(args.trace_i2c, project.trace_i2c if project else None, False)
        trace_spi = _coalesce(args.trace_spi, project.trace_spi if project else None, False)
        dump_iram = _coalesce(args.dump_iram, project.dump_iram if project else None, False)
        dump_sfr = _coalesce(args.dump_sfr, project.dump_sfr if project else None, False)
        watch_log = _coalesce(args.watch_log, project.watch_log if project else None, False)
        detect_tight_loops = _coalesce(
            args.tight_loop_detect,
            project.tight_loop_detect if project else None,
            True,
        )
        breakpoint_specs = _coalesce_list(project.breakpoints if project else (), args.breakpoint)
        watch_specs = _coalesce_list(project.watchpoints if project else (), args.watch)
        inspect_specs = _coalesce_list(project.inspect if project else (), args.inspect)
        dump_direct_specs = _coalesce_list(project.dump_direct if project else (), args.dump_direct)
        dump_xram_specs = _coalesce_list(project.dump_xram if project else (), args.dump_xram)
        step_limit = _coalesce(args.step, project.step_limit if project else None, None)

        runtime_hook = None
        if runtime_path:
            runtime_hook = make_runtime_hook(load_runtime_events(runtime_path))

        program = load_program(
            image,
            fmt=fmt,
            origin=origin,
            entry_point=entry,
        )

        symbol_file = load_symbol_file(symbols_path) if symbols_path else None
        symbols, source_map = merge_symbol_info(program.symbols, program.source_map, symbol_file)

        if args.list_symbols:
            _print_symbols(symbols)
            return 0

        breakpoints = resolve_breakpoints(breakpoint_specs, symbols)
        breakpoint_hook = make_breakpoint_hook(breakpoints) if breakpoints else None
        watch_monitor = None
        if watch_specs:
            watch_monitor = WatchpointMonitor(resolve_watchpoints(watch_specs, symbols))
        step_limiter = StepLimiter(step_limit) if step_limit is not None else None

        tracer: InstructionTracer | None = None
        if trace_file:
            tracer = InstructionTracer(
                trace_file,
                program.code_memory,
                symbols=symbols,
                source_map=source_map,
                limit=trace_limit,
            )

        def before_step(cpu: MCS51, tick: int) -> str | None:
            if runtime_hook is not None:
                runtime_hook(cpu, tick)
            if breakpoint_hook is not None:
                return breakpoint_hook(cpu, tick)
            return None

        cpu = MCS51(program.code_memory, entry_point=program.entry_point)
        if serial_input:
            cpu.queue_serial_input(serial_input)
        if serial_input_hex:
            cpu.queue_serial_input(_parse_hex_bytes(serial_input_hex))
        if watch_monitor is not None:
            watch_monitor.prime(cpu)

        try:
            def after_step(cpu: MCS51, previous_pc: int, opcode: int, instruction_index: int) -> str | None:
                if tracer is not None:
                    tracer.callback(cpu, previous_pc, opcode, instruction_index)
                if watch_monitor is not None:
                    halt = watch_monitor.callback(cpu, previous_pc, opcode, instruction_index)
                    if halt:
                        return halt
                if step_limiter is not None:
                    return step_limiter.callback(cpu, previous_pc, opcode, instruction_index)
                return None

            result = cpu.run(
                max_instructions=max_instructions,
                detect_tight_loops=detect_tight_loops,
                before_step=before_step,
                after_step=after_step if (tracer or watch_monitor or step_limiter) else None,
            )
        finally:
            if tracer is not None:
                tracer.close()
    except (
        DebugConfigError,
        LoaderError,
        ProjectConfigError,
        RuntimeConfigError,
        UnsupportedOpcodeError,
        ValueError,
    ) as exc:
        parser.error(str(exc))

    print(
        f"Loaded {program.format.upper()} image "
        f"0x{program.low_address:04X}-0x{program.high_address:04X}"
    )
    print(f"Halt reason: {result.halt_reason}")
    print(f"Instructions: {result.instructions}")
    print(f"Ticks: {result.ticks}")
    print("Serial output:")
    print(_format_serial(result.serial_output))
    _print_registers(cpu)

    if trace_file is not None:
        print(f"Trace file: {trace_file}")

    if watch_monitor is not None:
        _print_watch_log(watch_monitor, program.code_memory, symbols, source_map, force=watch_log)

    if trace_ports:
        if result.port_log:
            print("Port log:")
            for step, name, value in result.port_log:
                print(f"  [{step:06d}] {name}=0x{value:02X}")
        else:
            print("Port log: <no writes>")

    if trace_interrupts:
        if result.interrupt_log:
            print("Interrupt log:")
            for step, name, vector in result.interrupt_log:
                print(f"  [{step:06d}] {name} -> 0x{vector:04X}")
        else:
            print("Interrupt log: <none>")

    if trace_i2c:
        if result.i2c_log:
            print("I2C log:")
            for tick, desc in result.i2c_log:
                print(f"  [{tick:06d}] {desc}")
        else:
            print("I2C log: <no transactions>")

    if trace_spi:
        if result.spi_log:
            print("SPI log:")
            for tick, desc in result.spi_log:
                print(f"  [{tick:06d}] {desc}")
        else:
            print("SPI log: <no transactions>")

    if dump_iram:
        _print_nonzero_iram(cpu)

    if dump_sfr:
        _print_nonzero_sfr(cpu)

    _print_inspections(cpu, inspect_specs, symbols)

    for spec in dump_direct_specs:
        _print_direct_dump(cpu, spec)

    for spec in dump_xram_specs:
        _print_xram_dump(cpu, spec)

    return 0
